organization:
  name: Kohls

app:
  title: Scaffolded Ensemble App
  baseUrl: ${BASE_URL}

backend:
  baseUrl: ${BASE_URL}
  listen:
    port: 8080
  cors:
    origin: ${BASE_URL}
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  database:
    # config options: https://node-postgres.com/api/client
    client: pg
    connection:
      host: '127.0.0.1'
      port: 5432
      user: 'postgres'
      password: ${DB_PASSWORD}
  cache:
    store: memory

integrations:
  gitlab:
    - host: gitlab.com
      token: ${ENSEMBLE_GITLAB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  '/onboardingApi':
    target: 'http://localhost:8081'
    allowedMethods: ['POST', 'PUT', 'PATCH', 'GET']
    allowedHeaders: ['API-KEY','Content-Type', 'Accept', 'product_slug', 'project_slug']
    headers:
      API-KEY: '${API_KEY}'
  '/ensembleApi':
    target: 'http://localhost:8080'
    allowedMethods: ['GET']
    allowedHeaders: ['Content-Type','Accept']
  '/gitlabci':
    target: 'https://gitlab.com/api/v4'
    allowedMethods: ['GET']
    headers:
      PRIVATE-TOKEN: '${ENSEMBLE_GITLAB_TOKEN}'

techdocs:
  builder: 'external' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'googleGcs' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    googleGcs:
      bucketName: 'mygooglebucket'
      # We get credentials from location specified in GOOGLE_APPLICATION_CREDENTIALS env var

auth:
#  environment: development
  providers: {}
#  providers:
#    okta:
#      development:
#        clientId: ${AUTH_OKTA_CLIENT_ID}
#        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
#        audience: ${AUTH_OKTA_DOMAIN}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: ensemble-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group, Template]
  # Template gets inserted here to show in backstage
  # https://backstage.io/docs/features/software-templates/writing-templates
  # locations:
  #   - type: gitlab-discovery
  #     target: https://gitlab.com/kohls/products/blob/main/catalog-info.yaml
    # Kohls Example Teams
    # - type: url
    #   target: https://gitlab.com/kohls/products/backstage-portal/project-templates/-/blob/main/teams.yaml
    #   rules:
    #     - allow: [Component, System, API, Resource, Location, Group, domain, balanced-team]

