app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:8080
  cors:
    origin: http://localhost:3000
  database:
    client: better-sqlite3
    connection: ':memory:'

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
