site_name: Ensemble Readme
site_description: Readme file for Ensemble
site_author: Platform

theme:
# testing if this theme vs what A is using.
    name: material
    locale: en
    hljs_languages:
        - yaml
        - django
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

nav:
  - Home: index.md

plugins:
  - techdocs-core
